name: lint_mut_infect
description: Custom lint rule that encourages tracking mutated variables throughout the your codebase
version: 0.1.0
repository: https://github.com/0xNF/dart_lint_mut_infect

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
